<?php
/**
 * Created by PhpStorm.
 * User: Terry
 * Date: 4/17/2015
 * Time: 5:44 AM
 *
 * Run this script to prepare for deployment.
 * Minifies LESS generated style.css to scym-theme.min.css
 *
 * Requires Java installed: https://www.java.com
 *
 */

$themename='scymtheme';
$rootpath=realpath(__DIR__.'/../..');
$themeroot=$rootpath.'/sites/all/themes/'.$themename.'/';
$yuicompressor=__DIR__.'/yuicompressor.jar';

// minify css generated by LESS
$minifyCss = "java -jar $yuicompressor $themeroot".'less/style.css  > '.$themeroot.'assets/css/scym-theme.min.css';
echo 'Compressing CSS file...';
exec($minifyCss);
//echo "\n".$minifyCss; // for debugging

echo "\n\nDone\n";