<?php
/**
 *  Module for additional SCYM functions
 *
 * Load order:
 * Tops module most be loaded first
 * and scym module must be loaded before ckeditor (see scym_file_download($uri)
 * to ensure this load order run this query:
 *
 * UPDATE system SET weight= -4 WHERE NAME='tops' AND TYPE='module';
 * UPDATE system SET weight= -3 NAME='scym' AND TYPE='module';
 * UPDATE system SET weight= -2 NAME='scymtheme' AND TYPE = 'theme';
 *
 */
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_permission().
 */
function scym_permission()
{
    return array(
        'manage mailboxes' => array(
            'title' => 'Manage Mailboxes',
            'description' => 'Create and update mailboxes.'
        ),
        'administer registrations' => array(
            'title' => 'Administer Yearly Meeting Registations',
            'description' => 'Use all features of administration program.'
        ),
        'administer directory' => array(
            'title' => 'Administer Member Directory',
            'description' => 'Add and update persons and addresses in the directory.'
        ),

        'administer meeting directory' => array(
            'title' => 'Administer Meeting Directory',
            'description' => 'Add and meetings and worship groups in the directory.'
        ),

        'view directory' => array(
            'title' => 'View Member Directory',
            'description' => 'Access persons and addresses in the directory.'
        ),

        'register documents' => array(
            'title' => 'Register Document',
            'description' => 'Register uploaded document.'
        ),

        'manage web site tasks' => array(
            'title' => 'Manage Web Site Tasks',
            'description' => 'Add and update tasks.'
        ),

        'export directory' => array(
            'title' => 'Download member lists',
            'description' => 'Download directory lists as CSV files.'
        ),
        'administer housing' => array(
            'title' => 'Administer housing',
            'description' => 'Access registration housing system'
        ),
        'administer youth' => array(
            'title' => 'Administer youth program',
            'description' => 'Administer youth program.'
        ),
    );

}



function scym_handle_download($downloadType = null) {
    $downloadManager = new \App\sys\ScymDownloadManager();
    $lines = array();
    switch($downloadType) {
        case 'newsletter' :
            $lines = $downloadManager->getNewsletterList();
            break;
        case 'addresses' :
            $lines = $downloadManager->getAddressesList();
            break;
        case 'contacts' :
            $lines = $downloadManager->getContactsList();
            break;
        case 'transactions' :
            $lines = $downloadManager->getTransactionsList();
            break;
        case 'attendercounts' :
            $lines = $downloadManager->getAttenderCounts();
            break;
        case 'registrationcounts' :
            $lines = $downloadManager->getRegistrationCounts();
            break;
        case 'balancesheet' :
            $lines = $downloadManager->getBalanceSheet();
            break;
        case 'financesummary' :
            $lines = $downloadManager->getFinanceSummary();
            break;
        case 'campreport':
            $lines = $downloadManager->getCampReport();
            break;
        case 'nametags' :
            $lines = $downloadManager->getNameTags();
            break;
    }
    ob_start();
    header("Content-type: application/excel");header("Content-Disposition: attachment; filename=scym-$downloadType-list.csv");
    foreach ($lines as $line) {
        print $line;
    }
}

/**
 * Implements hook_menu().
 */
function scym_menu()
{
    $items = array();

    $items['scym/download'] = array(
        'page callback' => 'scym_handle_download',
        'access arguments' => array('export directory'), // 'access content'),
        'type' => MENU_CALLBACK,
    );


    return $items;

}

/**
 * Implements hook_file_download().
 *
 * The purpose of this function is to correct a problem with the ckeditor module.
 * When the module is installed it may disable protections for private file downloads.
 * For this to work, Tops must be loaded before ckeditor. See header notes.
 *
 */
function scym_file_download($uri)
{
    if (substr($uri,0,8) == 'private:') {
        $currentUser = Drupal::currentUser();
        return $currentUser->isAnonymous() ? -1 : null;
    }
    return null;
}

